// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module svm_speech_30_rtIsNaNF (
        ap_ready,
        value_r,
        ap_return
);


output   ap_ready;
input  [31:0] value_r;
output  [0:0] ap_return;

wire   [63:0] dc_fu_20_p1;
wire   [63:0] data_V_fu_24_p1;
wire   [10:0] fs_exp_V_fu_28_p4;
wire   [51:0] fs_sig_V_fu_38_p1;
wire   [0:0] icmp_ln1019_fu_42_p2;
wire   [0:0] icmp_ln1023_fu_48_p2;

svm_speech_30_fpext_32ns_64_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_1_no_dsp_1_U21(
    .din0(value_r),
    .dout(dc_fu_20_p1)
);

assign ap_ready = 1'b1;

assign data_V_fu_24_p1 = dc_fu_20_p1;

assign fs_exp_V_fu_28_p4 = {{data_V_fu_24_p1[62:52]}};

assign fs_sig_V_fu_38_p1 = data_V_fu_24_p1[51:0];

assign ap_return = (icmp_ln1023_fu_48_p2 & icmp_ln1019_fu_42_p2);

assign icmp_ln1019_fu_42_p2 = ((fs_exp_V_fu_28_p4 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln1023_fu_48_p2 = ((fs_sig_V_fu_38_p1 != 52'd0) ? 1'b1 : 1'b0);

endmodule //svm_speech_30_rtIsNaNF
